version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  league:
    container_name: league
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    volumes:
      - ./bin:/home/app/bin
      - ./tests:/home/app/tests
      - ./seeds:/home/app/seeds
      - ./src:/home/app/src
      - ./statics:/home/app/statics
      - ./manage.py:/home/app/manage.py
      - ./setup.py:/home/app/setup.py
    env_file:
      - env/.env.league
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s league:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 20010:5000
    depends_on:
      - league_cache
      - league_db
      - league_kafka
      - league_zookeeper
    networks:
      - app-net
  league_cache:
    container_name: league_cache
    image: redis:6
    restart: unless-stopped
    volumes:
      - cache_data:/var/libs/redis
    env_file:
      - env/.env.league_cache
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-net
  league_db:
    container_name: league_db
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.league_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U league" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
  league_kafka:
    container_name: league_kafka
    image: wurstmeister/kafka:latest
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/.env.league_kafka
    depends_on:
      - league_zookeeper
    networks:
      - app-net
  league_zookeeper:
    container_name: league_zookeeper
    image: wurstmeister/zookeeper:latest
    restart: on-failure
    env_file:
      - env/.env.league_zookeeper
    networks:
      - app-net
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - env/.env.league-redis-commander
    depends_on:
      - league_cache
    networks:
      - app-net
volumes:
  db_data:
networks:
  app-net:
    driver: bridge