version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  league:
    container_name: league
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    volumes:
      - ./bin:/home/app/bin
      - ./tests:/home/app/tests
      - ./seeds:/home/app/seeds
      - ./src:/home/app/src
      - ./statics:/home/app/statics
      - ./manage.py:/home/app/manage.py
      - ./setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.league
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s league:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 20010:5000
    depends_on:
      - league_db
    networks:
      - app-net
  league_cache:
    container_name: league_cache
    image: redis:6
    restart: unless-stopped
    volumes:
      - ${HUNCHO_DIR}/data/dev/league_cache/redis_data:/var/libs/redis
      - ${HUNCHO_DIR}/data/dev/league_cache/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.league_cache
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-net
  league_db:
    container_name: league_db
    image: postgres:9.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/league_db/data:/var/lib/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.league_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U league" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.league-redis-commander
    depends_on:
      - league_cache
    networks:
      - app-net
networks:
  app-net:
    driver: bridge